name = "portfolio-vite"
pages_build_output_dir = "dist"
compatibility_date = "2025-12-06"

[placement]
mode = "smart"

[limits]
cpu_ms = 10

[vars]
CONTENTFUL_SPACE_ID = "1u3dqblumu33"

[env.production.limits]
cpu_ms = 10

[env.production.vars]
CF_PAGES_URL = "https://tvdn.me"
CONTENTFUL_SPACE_ID = "1u3dqblumu33"
VITE_ENABLE_CF_IMAGE_TRANSFORM = "true"
